package com.mitron.connect.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

data class ConnectColorScheme(
    val surface1: Color,
    val surface2: Color,
    val surface3: Color,
    val chatBubbleMe: Color,
    val chatBubbleOther: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val border: Color,
    val borderStrong: Color,
    val borderStronger: Color,
    val fillPrimary: Color,
    val fillPrimaryDeep: Color,
    val onPrimary: Color,
    val accent: Color,
    val accentBg: Color,
    val pro: Color,
    val proBg: Color,
    val success: Color,
    val successBg: Color,
    val danger: Color,
    val dangerBg: Color,
    val warn: Color,
    val warnBg: Color,
)

val LightConnectColors = ConnectColorScheme(
    surface1         = SurfaceLight1,
    surface2         = SurfaceLight2,
    surface3         = SurfaceLight3,
    chatBubbleMe     = ChatBubbleMeLight,
    chatBubbleOther  = ChatBubbleOtherLight,
    textPrimary      = TextPrimaryLight,
    textSecondary    = TextSecondaryLight,
    textMuted        = TextMutedLight,
    border           = BorderLight,
    borderStrong     = BorderStrongLight,
    borderStronger   = BorderStrongerLight,
    fillPrimary      = BrandBlue,
    fillPrimaryDeep  = BrandBlueDeep,
    onPrimary        = OnBrandBlue,
    accent           = AccentTealLight,
    accentBg         = AccentTealBgLight,
    pro              = AiIndigo,
    proBg            = AiIndigoBgLight,
    success          = SuccessGreen,
    successBg        = SuccessBgLight,
    danger           = DangerRed,
    dangerBg         = DangerBgLight,
    warn             = WarnAmber,
    warnBg           = WarnBgLight,
)

val DarkConnectColors = ConnectColorScheme(
    surface1         = SurfaceDark1,
    surface2         = SurfaceDark2,
    surface3         = SurfaceDark3,
    chatBubbleMe     = ChatBubbleMeDark,
    chatBubbleOther  = ChatBubbleOtherDark,
    textPrimary      = TextPrimaryDark,
    textSecondary    = TextSecondaryDark,
    textMuted        = TextMutedDark,
    border           = BorderDark,
    borderStrong     = BorderStrongDark,
    borderStronger   = BorderStrongerDark,
    fillPrimary      = BrandBlue,
    fillPrimaryDeep  = BrandBlueDeep,
    onPrimary        = OnBrandBlue,
    accent           = AccentTealDark,
    accentBg         = AccentTealBgDark,
    pro              = AiIndigo,
    proBg            = AiIndigoBgDark,
    success          = SuccessGreen,
    successBg        = SuccessBgDark,
    danger           = DangerRed,
    dangerBg         = DangerBgDark,
    warn             = WarnAmber,
    warnBg           = WarnBgDark,
)

val LocalConnectColors = staticCompositionLocalOf { LightConnectColors }
